# -*- coding: utf-8 -*-
"""FinalProject3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1370F4rAeyXgNTgfvQZ0Ar_ERf3LDPT9_
"""

#model prediction using k-Nearest Neighbours
from google.colab import drive 
drive.mount('/content/drive/')
import os 
path='/content/drive/My Drive/AI_Lab_144175'
os.chdir(path)

import pandas as pd
import numpy as np
disease=pd.read_csv("diabetes_prediction_dataset.csv")
disease.head()

#disease.isnull().sum() #check missing values in columns
#disease.isna().sum()  #check nan values in the dataset in each column
#calculate how much data in each column

# Handle duplicates
duplicate_rows_data = disease[disease.duplicated()]
print("number of duplicate rows: ", duplicate_rows_data.shape)
#drop duplicates
disease = disease.drop_duplicates()#the number of unique values
for column in disease.columns:
    num_distinct_values = len(disease[column].unique())
    print(f"{column}: {num_distinct_values} distinct values")


# Checking null values
print(disease.isnull().sum())

#Categorical encoding (columns with non numerical data)
from sklearn.preprocessing import OrdinalEncoder
columns = ["gender", "smoking_history"]
encoding = OrdinalEncoder()
disease[columns] = encoding.fit_transform(disease[columns])
disease.head()

from sklearn.model_selection import train_test_split
y=disease.diabetes
disease_features = ['gender', 'age', 'hypertension', 'heart_disease', 
                        'smoking_history', 'bmi', 'HbA1c_level','blood_glucose_level']
X = disease[disease_features]
#another implementatiom for x = disease.drop(['diabetes'], axis=1)
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

#disease.shape,train_X.shape,val_X.shape
#train_y.shape,val_y.shape

# import KNeighbors ClaSSifier from sklearn
from sklearn.neighbors import KNeighborsClassifier


# instantiate the model
knn = KNeighborsClassifier(n_neighbors=3)


# fit the model to the training set
knn.fit(train_X, train_y)

preds = knn.predict(val_X)

preds

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score
print("mean_absolute_error ",mean_absolute_error(val_y, preds))
accuracy = accuracy_score(val_y, preds.round())
print('Accuracy:', accuracy)
print('Accuracy:', int(accuracy*100),"%")

# View confusion matrix for test data and predictions
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
confusion_matrix(val_y, preds.round())

# View the classification report for test data and predictions
print(classification_report(val_y, preds.round()))